apiVersion: v1
kind: Service
metadata:
  name: {{ template "simplytest.fullname" . }}
  labels:
    app: {{ template "simplytest.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    host: {{ .Release.Name }}.{{ .Values.domain }}
  annotations:
    proxy_host: "{{ .Release.Name }}.{{ .Values.domain }}"
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: {{ template "simplytest.name" . }}
    release: {{ .Release.Name }}
